version: '3.8'
services:
  api:
    build: ./Backend
    container_name: ball_api
    restart: always
    ports:
      - '8080:8080'
    volumes:
      - ./Backend:/opt/app/api
    networks:
      - ln_network
  web:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: ball_frontend
    restart: always
    ports:
      - "3000:3000"
    networks:
      - ln_network

networks:
  ln_network:
    driver: bridge