version: '3.8'
services:
  api:
    build: ./Backend
    container_name: ln_api
    restart: always
    ports:
      - '8888:8888'
    volumes:
      - ./Backend:/opt/app/api
    networks:
      - ln_network
  web:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: ln_frontend
    restart: always
    ports:
      - "3333:3333"
    networks:
      - ln_network
    command: "npm run start"

networks:
  ln_network:
    driver: bridge