version: '3.8'
services:
  db:
    image: postgres:alpine
    container_name: ln_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
    networks:
      - ln_network
  api:
    build: ./Backend
    container_name: ln_api
    restart: always
    ports:
      - '8888:8888'
    volumes:
      - ./Backend:/opt/app/api
    networks:
      - ln_network
  web:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: ln_frontend
    restart: always
    ports:
      - "3333:3333"
    networks:
      - ln_network
    command: "npm run start"
volumes:
  db:
    driver: local
networks:
  ln_network:
    driver: bridge